//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kairos.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kairos.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity about to be deleted.
        /// </summary>
        internal static string ActivityAboutToBeDeleted {
            get {
                return ResourceManager.GetString("ActivityAboutToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Properties.
        /// </summary>
        internal static string ActivityProperties {
            get {
                return ResourceManager.GetString("ActivityProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kairos files (*.kai)|*.kai|Json files (*json)|*.json.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project about to be deleted.
        /// </summary>
        internal static string ProjectAboutToBeDeleted {
            get {
                return ResourceManager.GetString("ProjectAboutToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Collection Properties.
        /// </summary>
        internal static string ProjectCollectionProperties {
            get {
                return ResourceManager.GetString("ProjectCollectionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Properties.
        /// </summary>
        internal static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall activity{0} be deleted?.
        /// </summary>
        internal static string ShallActivityBeDeleted {
            get {
                return ResourceManager.GetString("ShallActivityBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall project {0} be deleted with all its activities?.
        /// </summary>
        internal static string ShallProjectBeDeleted {
            get {
                return ResourceManager.GetString("ShallProjectBeDeleted", resourceCulture);
            }
        }
    }
}
